### PR TITLE
fix order of MAPPO reshape in MPE & Hanabi

### PR DESCRIPTION
**Pull request by amacrutherford**
also remove done masking in MPE as this doesn't seem to do anything. Instigated by #85

### CODE REVIEW

**Comment by mttga** [comment]
hey alex you inadvertently pushed your user in [mappo_homogenous_rnn_hanabi.yaml](https://github.com/FLAIROx/JaxMARL/pull/87/files#diff-b204beb1b655085327a876984fe802f5bb58c1331d262420e7b8f185e746f711). Same for start_wandb_sweep.py I guess?

**Comment by amacrutherford** [comment]
Yep am running the sweep on this branch, will clean it up before we merge
:)

**Comment by mttga** [comment]
ah ok sweet :)

**Review by mttga — APPROVED** [review]
great!

**Pull request merged**
