### PR TITLE
JaxNav, base class update, version increment, scipy bound

### PR DESCRIPTION
**Pull request by amacrutherford**

### CODE REVIEW

**Comment by amacrutherford** [comment]
Couple of things:
- JaxNav environment (gif of this replaces switch riddle in the readme collage)
- Update to `step` to allow for autoresets to a specified state, this should not change any current functionality
- scipy bounded to =<1.12 as i experienced a bug with 1.13.1

**Comment by benellis3** [comment]
Have we checked the other environments run with that version of SciPy? If not would be good to check that before merging

**Comment by amacrutherford** [comment]
this is a good point, I have added random action rollout tests for the other environments (i.e. rollout 10 steps to make sure no errors are thrown). Will also do this for the learning scripts, maybe train for like 2000 environment timesteps or smth just to check everything runs

**Comment by mttga** [comment]
do we want to include the tests for the learning scripts? Or are we happy with the new environment tests (which look good) for this PR?

**Comment by amacrutherford** [comment]
> do we want to include the tests for the learning scripts? Or are we happy with the new environment tests (which look good) for this PR?

have now added :slightly_smiling_face:, let me know what ya think

**Review by mttga — APPROVED** [review]
great PR, lgtm and welcome jaxnav!

**Pull request merged**
